/**
 * Mock data for landing page development
 * 
 * Provides extended event data with social proof, featured calendars,
 * cities, and testimonials for the redesigned landing page.
 */

import { ExtendedEvent } from '@/components/shared/EventCard';
import { FeaturedCalendar } from '@/components/shared/FeaturedCalendarCard';
import { City } from '@/components/shared/CityCard';
import { Testimonial } from '@/components/shared/TestimonialCard';

/**
 * Extended mock events with social proof and trending data
 */
export const mockLandingEvents: ExtendedEvent[] = [
  {
    id: '1',
    name: 'Jazz Night at Blue Note',
    description: 'Experience live jazz performances from world-class musicians',
    date: new Date('2024-12-15T20:00:00'),
    location: 'New York',
    category: 'Music',
    image: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=500&h=300&fit=crop',
    organizer: { id: 'org1', name: 'Blue Note Jazz Club', followerCount: 5200 },
    ticketTypes: [{ id: 't1', eventId: '1', name: 'General', price: 50, quantity: 100, sold: 55, type: 'regular' }],
    status: 'active',
    createdAt: new Date(),
    totalAttendees: 55,
    organizerId: 'org1',
    interestedCount: 342,
    goingCount: 128,
    isFeatured: true,
    isTrending: true,
    trendingRank: 1,
    ticketAvailabilityPercent: 45,
  },
  {
    id: '2',
    name: 'Tech Conference 2024',
    description: 'Annual technology conference featuring keynotes from industry leaders',
    date: new Date('2024-12-17T09:00:00'),
    location: 'San Francisco',
    category: 'Tech',
    image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=500&h=300&fit=crop',
    organizer: { id: 'org2', name: 'Tech Events Inc', followerCount: 8900 },
    ticketTypes: [{ id: 't2', eventId: '2', name: 'Standard', price: 100, quantity: 500, sold: 125, type: 'regular' }],
    status: 'active',
    createdAt: new Date(),
    totalAttendees: 125,
    organizerId: 'org2',
    interestedCount: 1250,
    goingCount: 456,
    isFeatured: true,
    isTrending: true,
    trendingRank: 2,
    ticketAvailabilityPercent: 75,
  },
  {
    id: '3',
    name: 'Free Yoga in the Park',
    description: 'Morning yoga session in Central Park - all levels welcome',
    date: new Date('2024-12-16T07:00:00'),
    location: 'New York',
    category: 'Health & Wellness',
    image: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=500&h=300&fit=crop',
    organizer: { id: 'org3', name: 'NYC Yoga Community', followerCount: 3400 },
    ticketTypes: [{ id: 't3', eventId: '3', name: 'Free', price: 0, quantity: 200, sold: 24, type: 'regular' }],
    status: 'active',
    createdAt: new Date(),
    totalAttendees: 24,
    organizerId: 'org3',
    interestedCount: 567,
    goingCount: 234,
    isFeatured: false,
    isTrending: true,
    trendingRank: 3,
    ticketAvailabilityPercent: 88,
  },
  {
    id: '4',
    name: 'Food Festival LA',
    description: 'International food festival featuring cuisines from around the world',
    date: new Date('2024-12-18T11:00:00'),
    location: 'Los Angeles',
    category: 'Food & Drink',
    image: 'https://images.unsplash.com/photo-1555939594-58d7cb561404?w=500&h=300&fit=crop',
    organizer: { id: 'org4', name: 'LA Food Events', followerCount: 6700 },
    ticketTypes: [{ id: 't4', eventId: '4', name: 'Entry', price: 25, quantity: 1000, sold: 80, type: 'regular' }],
    status: 'active',
    createdAt: new Date(),
    totalAttendees: 80,
    organizerId: 'org4',
    interestedCount: 2100,
    goingCount: 890,
    isFeatured: true,
    isTrending: true,
    trendingRank: 4,
    ticketAvailabilityPercent: 92,
  },
  {
    id: '5',
    name: 'Comedy Night with Dave Chappelle',
    description: 'Stand-up comedy show featuring Dave Chappelle and special guests',
    date: new Date('2024-12-19T20:00:00'),
    location: 'Chicago',
    category: 'Comedy',
    image: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=500&h=300&fit=crop',
    organizer: { id: 'org5', name: 'Comedy Central', followerCount: 12000 },
    ticketTypes: [{ id: 't5', eventId: '5', name: 'General', price: 75, quantity: 300, sold: 276, type: 'regular' }],
    status: 'active',
    createdAt: new Date(),
    totalAttendees: 276,
    organizerId: 'org5',
    interestedCount: 3400,
    goingCount: 1200,
    isFeatured: true,
    isTrending: true,
    trendingRank: 5,
    ticketAvailabilityPercent: 8,
    saleEndsAt: new Date(Date.now() + 12 * 60 * 60 * 1000), // 12 hours from now
  },
  {
    id: '6',
    name: 'Design Workshop',
    description: 'Learn modern UI/UX design principles from industry experts',
    date: new Date('2024-12-20T14:00:00'),
    location: 'New York',
    category: 'Design',
    image: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=500&h=300&fit=crop',
    organizer: { id: 'org6', name: 'Design Academy', followerCount: 4500 },
    ticketTypes: [{ id: 't6', eventId: '6', name: 'Workshop', price: 45, quantity: 50, sold: 45, type: 'regular' }],
    status: 'active',
    createdAt: new Date(),
    totalAttendees: 45,
    organizerId: 'org6',
    interestedCount: 234,
    goingCount: 45,
    isFeatured: false,
    isTrending: true,
    trendingRank: 6,
    ticketAvailabilityPercent: 10,
  },
  {
    id: '7',
    name: 'Marathon 2024',
    description: 'Annual city marathon - 5K, 10K, and full marathon options',
    date: new Date('2024-12-21T07:00:00'),
    location: 'Boston',
    category: 'Sports',
    image: 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=500&h=300&fit=crop',
    organizer: { id: 'org7', name: 'Boston Sports Events', followerCount: 7800 },
    ticketTypes: [
      { id: 't7a', eventId: '7', name: '5K', price: 30, quantity: 500, sold: 175, type: 'regular' },
      { id: 't7b', eventId: '7', name: '10K', price: 50, quantity: 300, sold: 150, type: 'regular' },
      { id: 't7c', eventId: '7', name: 'Full Marathon', price: 100, quantity: 200, sold: 70, type: 'regular' },
    ],
    status: 'active',
    createdAt: new Date(),
    totalAttendees: 395,
    organizerId: 'org7',
    interestedCount: 1800,
    goingCount: 650,
    isFeatured: false,
    isTrending: true,
    trendingRank: 7,
    ticketAvailabilityPercent: 65,
  },
  {
    id: '8',
    name: 'Networking Mixer',
    description: 'Connect with professionals in tech and entrepreneurship',
    date: new Date('2024-12-22T18:00:00'),
    location: 'San Francisco',
    category: 'Networking',
    image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=500&h=300&fit=crop',
    organizer: { id: 'org8', name: 'Tech Networking', followerCount: 5600 },
    ticketTypes: [{ id: 't8', eventId: '8', name: 'Entry', price: 20, quantity: 200, sold: 90, type: 'regular' }],
    status: 'active',
    createdAt: new Date(),
    totalAttendees: 90,
    organizerId: 'org8',
    interestedCount: 456,
    goingCount: 178,
    isFeatured: false,
    isTrending: true,
    trendingRank: 8,
    ticketAvailabilityPercent: 55,
  },
  {
    id: '9',
    name: 'Art Exhibition Opening',
    description: 'Contemporary art exhibition featuring emerging artists',
    date: new Date('2024-12-23T19:00:00'),
    location: 'Los Angeles',
    category: 'Art',
    image: 'https://images.unsplash.com/photo-1578301978162-7aae4d755744?w=500&h=300&fit=crop',
    organizer: { id: 'org9', name: 'LA Art Gallery', followerCount: 3200 },
    ticketTypes: [{ id: 't9', eventId: '9', name: 'General', price: 15, quantity: 300, sold: 66, type: 'regular' }],
    status: 'active',
    createdAt: new Date(),
    totalAttendees: 66,
    organizerId: 'org9',
    interestedCount: 678,
    goingCount: 234,
    isFeatured: false,
    isTrending: true,
    trendingRank: 9,
    ticketAvailabilityPercent: 78,
  },
  {
    id: '10',
    name: 'Music Festival',
    description: 'Three-day music festival with multiple stages and artists',
    date: new Date('2024-12-24T12:00:00'),
    location: 'Miami',
    category: 'Music',
    image: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=500&h=300&fit=crop',
    organizer: { id: 'org10', name: 'Miami Music Events', followerCount: 9200 },
    ticketTypes: [
      { id: 't10a', eventId: '10', name: 'Day Pass', price: 60, quantity: 1000, sold: 600, type: 'regular' },
      { id: 't10b', eventId: '10', name: '3-Day Pass', price: 150, quantity: 500, sold: 200, type: 'regular' },
    ],
    status: 'active',
    createdAt: new Date(),
    totalAttendees: 800,
    organizerId: 'org10',
    interestedCount: 4500,
    goingCount: 1800,
    isFeatured: true,
    isTrending: true,
    trendingRank: 10,
    ticketAvailabilityPercent: 40,
  },
];

/**
 * Featured calendars for the FeaturedCalendars section
 */
export const mockFeaturedCalendars: FeaturedCalendar[] = [
  {
    id: 'cal1',
    name: 'NYC Tech Events',
    description: 'All the best tech events happening in New York City',
    image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=500&h=300&fit=crop',
    followerCount: 12500,
    eventCount: 245,
  },
  {
    id: 'cal2',
    name: 'Music Lovers',
    description: 'Curated music events from concerts to festivals',
    image: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=500&h=300&fit=crop',
    followerCount: 18900,
    eventCount: 567,
  },
  {
    id: 'cal3',
    name: 'Foodie Adventures',
    description: 'Food festivals, tastings, and culinary experiences',
    image: 'https://images.unsplash.com/photo-1555939594-58d7cb561404?w=500&h=300&fit=crop',
    followerCount: 9800,
    eventCount: 342,
  },
  {
    id: 'cal4',
    name: 'Wellness & Fitness',
    description: 'Yoga, fitness classes, and wellness workshops',
    image: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=500&h=300&fit=crop',
    followerCount: 15600,
    eventCount: 423,
  },
  {
    id: 'cal5',
    name: 'Comedy Central',
    description: 'Stand-up comedy shows and comedy festivals',
    image: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=500&h=300&fit=crop',
    followerCount: 22300,
    eventCount: 189,
  },
  {
    id: 'cal6',
    name: 'Art & Culture',
    description: 'Art exhibitions, theater, and cultural events',
    image: 'https://images.unsplash.com/photo-1578301978162-7aae4d755744?w=500&h=300&fit=crop',
    followerCount: 11200,
    eventCount: 298,
  },
];

/**
 * Popular cities for the PopularCities section
 */
export const mockPopularCities: City[] = [
  {
    id: 'ny',
    name: 'New York',
    image: 'https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=500&h=400&fit=crop',
    eventCount: 1250,
  },
  {
    id: 'la',
    name: 'Los Angeles',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=500&h=400&fit=crop',
    eventCount: 980,
  },
  {
    id: 'sf',
    name: 'San Francisco',
    image: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=500&h=400&fit=crop',
    eventCount: 750,
  },
  {
    id: 'chicago',
    name: 'Chicago',
    image: 'https://images.unsplash.com/photo-1494522510464-1a2f3a52f203?w=500&h=400&fit=crop',
    eventCount: 720,
  },
  {
    id: 'miami',
    name: 'Miami',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=500&h=400&fit=crop',
    eventCount: 680,
  },
  {
    id: 'boston',
    name: 'Boston',
    image: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=500&h=400&fit=crop',
    eventCount: 560,
  },
  {
    id: 'seattle',
    name: 'Seattle',
    image: 'https://images.unsplash.com/photo-1511632765486-a01980e01a18?w=500&h=400&fit=crop',
    eventCount: 490,
  },
  {
    id: 'denver',
    name: 'Denver',
    image: 'https://images.unsplash.com/photo-1511632765486-a01980e01a18?w=500&h=400&fit=crop',
    eventCount: 410,
  },
];

/**
 * Testimonials for the SocialProofSection
 */
export const mockTestimonials: Testimonial[] = [
  {
    id: 'test1',
    quote: 'Found the most amazing jazz concert through this platform. The event discovery experience is unmatched!',
    author: 'Sarah Johnson',
    source: 'App Store Review',
    rating: 5,
  },
  {
    id: 'test2',
    quote: 'As an organizer, this platform made it so easy to set up my first event. Highly recommended!',
    author: 'Michael Chen',
    source: 'Google Play Review',
    rating: 5,
  },
  {
    id: 'test3',
    quote: 'Love how I can discover events based on my interests. The personalization is spot on.',
    author: 'Emma Rodriguez',
    source: 'Twitter',
    rating: 5,
  },
  {
    id: 'test4',
    quote: 'Best event discovery app I\'ve used. The interface is intuitive and the events are always fresh.',
    author: 'David Park',
    source: 'App Store Review',
    rating: 5,
  },
  {
    id: 'test5',
    quote: 'Organized 3 events on this platform and the support team was incredibly helpful throughout.',
    author: 'Jessica Williams',
    source: 'LinkedIn',
    rating: 5,
  },
  {
    id: 'test6',
    quote: 'The location-based event discovery helped me find events I never would have known about!',
    author: 'Alex Thompson',
    source: 'Facebook',
    rating: 5,
  },
];

/**
 * Trust metrics for the SocialProofSection
 */
export const mockTrustMetrics = {
  organizers: 5000,
  eventsHosted: 50000,
};

